### ISSUE TITLE
[feature] Add option to insert the question list at the cursor

### ISSUE THREAD

**Issue by ironfroggy** [ShockThunder/RandomStructuralDiary#4]
I don't want to append the list to the very end of my current note, so inserting it at the cursor location would allow me to control where its put.

**Comment by ShockThunder** [comment]
Sounds reasonable. I will take a look at the API.

**Comment by ShockThunder** [comment]
> I don't want to append the list to the very end of my current note, so inserting it at the cursor location would allow me to control where its put.

Added in 1.1.2 release. Please update and check.
